apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: app-nginx
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: triple3a/temp-project:latest
          ports:
            - containerPort: 8080
