apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: app-nginx
  labels:
    app: app
spec:
  selector:
    app: app
  type: NodePort
  ports:
    - name: app
      port: 8080
      targetPort: 8080
